name: K8s Status Line
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - darwin
        goarch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5

      - name: build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build k8s_status_line.go

      - name: publish
        uses: actions/upload-artifact@v2
        with:
          name: k8s-status-line-${{ matrix.goos }}-${{ matrix.goarch }}
          path: k8s_status_line
